Added Redux
nikolairoshchin/TaskManager pull request #17
Opened 2022-09-29 09:11 UTC by nikolairoshchin

2022-09-29 19:28 UTC, greybutton requested changes

2022-09-29 19:28 UTC, greybutton commented on app/javascript/App.js
> +function App() {
почему такой синтаксис?

2022-09-29 19:28 UTC, greybutton commented on app/javascript/MUITheme/MUITheme.js
> +const MUITheme = () => {};
с таким кодом работаем mui стили?

2022-09-29 19:28 UTC, greybutton commented on app/javascript/containers/TaskBoard.js
> +import TasksRepository from 'repositories/TasksRepository';
создание, обновление и т.д. нужно вынести в слайсы. в слайсе использовать репозиторий, а в компоненте функции от слайса

2022-09-29 20:01 UTC, nikolairoshchin commented on app/javascript/App.js
> +function App() {
Linter исправляет именно на такой синтаксис если запустить его с --fix.

2022-09-29 20:04 UTC, nikolairoshchin commented on app/javascript/MUITheme/MUITheme.js
> +const MUITheme = () => {};
Пардон, забыл про него совсем. Задача не поставлена, а спросить забыл. 
Что  данный компонент должен делать? Реализовать MUI темы - светлую и темную?

2022-09-30 08:09 UTC, greybutton commented on app/javascript/App.js
> +function App() {
хм, ок

2022-09-30 08:10 UTC, greybutton commented on app/javascript/MUITheme/MUITheme.js
> +const MUITheme = () => {};
добавить стилей из MUI темы, чтобы у кнопок и т.п. были какие то стили, переключение тем не нужно

2022-10-03 06:51 UTC, nikolairoshchin commented on app/javascript/containers/TaskBoard.js
> +import TasksRepository from 'repositories/TasksRepository';
Если я выношу создание, обновление в слайс, то как быть с состоянием интерфейса? handleOpenAddPopup, handleOpenEditPopup и самое главное, handleClose? Выносить в отдельный слайс с сохранением состояния в редукс? Или хранить состояние интерфейса в компоненте?

2022-10-03 07:46 UTC, greybutton commented on app/javascript/containers/TaskBoard.js
> +import TasksRepository from 'repositories/TasksRepository';
в компоненте

2022-10-04 06:24 UTC, greybutton requested changes

2022-10-04 06:24 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +import useViewMode from 'hooks/store/useViewMode';
зачем это в слайсе? раз вынес в хук, то используй его в компоненте, в слайсах что с бэкендом взаимодействует

2022-10-04 06:24 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +import TaskForm from 'forms/TaskForm';
перемешаны импорты библиотек и локальный файлов

2022-10-04 06:39 UTC, nikolairoshchin commented on app/javascript/slices/TasksSlice.js
> +import useViewMode from 'hooks/store/useViewMode';
Дело в том, что в слайсе, в функциях handleTaskCreate, handleTaskUpdate, handleTaskDestroy вызывается handleClose. И она же передается в компоненте. И как её использовать и там, и там я не нашел другого способа. Подскажите, пожалуйста, в какую сторону копать?

2022-10-04 10:06 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +import useViewMode from 'hooks/store/useViewMode';
можно в компоненте создать функцию, которая будет внутри себя вызывать слайсовую функцию и после успешного завершения вызывать функцию закрытия

2022-10-05 07:05 UTC, greybutton approved these changes

2022-10-05 08:29 UTC, merged