Added newrelic
nikolairoshchin/TaskManager pull request #25
Opened 2022-10-11 11:48 UTC by nikolairoshchin

2022-10-11 18:16 UTC, greybutton requested changes

2022-10-11 18:16 UTC, greybutton commented on config/newrelic.yml
> +  license_key: eu01xx654aa2eff934ccabe96d0fd501f04eNRAL
токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)

2022-10-12 19:03 UTC, greybutton requested changes

2022-10-12 19:03 UTC, greybutton commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
зачем это? и где нашел?

2022-10-13 05:12 UTC, nikolairoshchin commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
Для того, чтобы убрать токен из файла конфигурации и передать его в виде переменной. Я использовал неправильный метод? Не нашел как еще можно загрузить токен не прописывая его в явном виде.
В файле env_set.rb хранится ключ и имя переменной. Здесь она загружается.
Найдена, по-моему на стековерфлоу.

2022-10-13 05:12 UTC, nikolairoshchin commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
Да, и env_set.rb добавлен в .gitignore

2022-10-13 06:13 UTC, greybutton commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
по идее так же как для роллбара токен, добавить в переменные среды

2022-10-13 08:13 UTC, nikolairoshchin commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
Прошу прощения - может я совсем не правильно понимаю задачу? Мы можем передать значение в переменные среды либо: 
указав в командной строке при запуске
в файле .env (для докера). Либо в стороннем файле как у меня сделано.
в явном виде в docker-compose.yml.

Во всех случаях токен будет виден, если не добавить файл в гитигноре. Мы хотим ведь полностью скрыть токен? Тогда я чего то не понимаю. Прошу помощь зала :)

2022-10-13 12:03 UTC, nikolairoshchin commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
Ну еще вариант dotenv & figaro. Но, по сути, это тоже .env

2022-10-13 19:49 UTC, greybutton commented on config/environment.rb
> +load(app_env) if File.exist?(app_env)
> Мы хотим ведь полностью скрыть токен?

да, поэтому мы его добавляем только в переменные среды CI, для разработки можно в докеркомпозе задать фейковую строчку для переменной (самый простой способ)

2022-10-15 10:44 UTC, greybutton approved these changes

2022-10-17 06:13 UTC, merged